Update README.md
sozykin/ml_fastapi_tests pull request #5
Opened 2022-04-24 16:32 UTC by sozykin

Я сделал описание проекта в README.md более понятным для пользователей.

Основные изменения:

- Добавлено описание пайплайна, который используется в приложении.

2022-04-25 05:04 UTC, urfu-colab commented on README.md
> +В примере используется пайплайн "sentiment-analysis" без указания модели.
Предлагаю добавить ссылку на пайплайн на сайте https://huggingface.co/tasks/text-classification

2022-04-25 05:09 UTC, sozykin commented on README.md
> +В примере используется пайплайн "sentiment-analysis" без указания модели.
Ссылку добавил.

2022-04-25 05:34 UTC, urfu-colab approved these changes
Все корректно, можно сливать.

2022-04-25 06:03 UTC, urfu-colab requested changes
Название в README на английском, а текст описания на русском.
Все должно быть на одном языке.
Или README на двух языках: на русском или английском. Но каждый вариант должен содержать название и описание.

2023-04-24 16:07 UTC, alduinsh approved these changes
approve your update

2025-03-24 13:48 UTC, merged